// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92ypdBLaYrOzX-ueEZvvahWeCBz0MVNI',
    appId: '1:63889904539:web:40bf43b8572c3db247073e',
    messagingSenderId: '63889904539',
    projectId: 'al-walla',
    authDomain: 'al-walla.firebaseapp.com',
    storageBucket: 'al-walla.firebasestorage.app',
    measurementId: 'G-N1JBF578S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_L774memB8Thfg9ddGcnXJjLzedLhaE',
    appId: '1:63889904539:android:0b5c854d6c8a040747073e',
    messagingSenderId: '63889904539',
    projectId: 'al-walla',
    storageBucket: 'al-walla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARyaqR0QdF4ac1oH64LARdPfGgJVP5lj0',
    appId: '1:63889904539:ios:aa2b696c6a40b8e447073e',
    messagingSenderId: '63889904539',
    projectId: 'al-walla',
    storageBucket: 'al-walla.firebasestorage.app',
    iosBundleId: 'com.example.alWallaTeam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARyaqR0QdF4ac1oH64LARdPfGgJVP5lj0',
    appId: '1:63889904539:ios:aa2b696c6a40b8e447073e',
    messagingSenderId: '63889904539',
    projectId: 'al-walla',
    storageBucket: 'al-walla.firebasestorage.app',
    iosBundleId: 'com.example.alWallaTeam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA92ypdBLaYrOzX-ueEZvvahWeCBz0MVNI',
    appId: '1:63889904539:web:9b82b60f16ed081447073e',
    messagingSenderId: '63889904539',
    projectId: 'al-walla',
    authDomain: 'al-walla.firebaseapp.com',
    storageBucket: 'al-walla.firebasestorage.app',
    measurementId: 'G-SKMWT188VF',
  );
}
